<?xml version="1.0" encoding="utf-8"?><Database Name="sampledata" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FRANK-PC\FRANK2014;Initial Catalog=sampledata;Integrated Security=True" SettingsObjectName="SmackdownEF6vsLinq2SQL.Properties.Settings" SettingsPropertyName="sampledataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="last" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="department" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>